config/routes.rb
TestApp::Application.routes.draw do

  get "stats/index"
  get "stats/show"
  post "stats/search"

  resources :notifications do
    collection do
      post 'delete'
    end
    collection do
      get 'reload'
    end
  end

  resources :games do
    collection do
      post 'by_user'
    end

    member do
      get 'user'
      get 'add_unit'
      get 'move_unit'
      post 'end_turn'
      post 'surrender'
    end
  end

  get "welcome/index"

  devise_for :users

  resources :maps do
    collection do
      get 'for_user'
    end
    member do
      post 'vote'
      post 'publish'
      post 'unpublish'
    end
  end

  root :to => 'welcome#index'

end

app/models/map.rb
class Map < ActiveRecord::Base
  belongs_to :user
  has_many :tiles
  accepts_nested_attributes_for :tiles

  has_many :map_votes

  validates :height, :width, :numericality => {  
                              :only_integer => true, 
                              :greater_than => 4, 
                              :less_than_or_equal_to => 20 }


  validates :name, :length => { :minimum => 3, :maximum => 40 }

  before_create :generate_tiles

  def generate_tiles
  	unless self.real_map_id.nil?
      clone_tiles_from_parent
      return
    end

  	default_tile_type = TileType.first	# Open Water

    for y in 0..self.height-1
	  	for x in 0..self.width-1
	  		t = Tile.new
	  		t.x = x
	  		t.y = y
	  		t.tile_type = default_tile_type
	  		self.tiles << t
  		end
  	end
  end

  def clone_tiles_from_parent
    parent_map = Map.find(self.real_map_id)

    for tile in parent_map.tiles
      self.tiles << tile.dup
    end
  end

  def get_tile_at(x,y)
    return nil if x < 0 or y < 0 or x >= self.width or y >= self.height

    if self.tiles.loaded?
      return self.tiles[y*self.width + x]
    else
      return Tile.where(:map_id => self.id, :x => x, :y => y).first
    end
  end

  def update_vote_total!
    self.vote_total = MapVote.where(:map_id => self.id).sum('vote')
    self.save!
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  # GET /maps
  # GET /maps.json
  def index

    per_page= 20

    if current_user.nil?
      @maps = Map.where(:real_map_id => nil, :published => true).includes(:user).order("vote_total DESC").paginate(:page => params[:page], :per_page => per_page)
    else
      # Only display my maps on the first page
      # Currently the first page will have more entries than per_page if the user has maps
      # We can change per_page on page #1 to correct this, but then page 2 will skip
      # some maps innapropriately unless we fiddle with offsets or something.
      if params[:page].nil? or params[:page].to_i == 1
        @my_maps = Map.where(:real_map_id => nil).where("user_id = #{current_user.id}").includes(:user).order("vote_total DESC")
      end

      @maps = Map.where(:real_map_id => nil, :published => true).where("user_id <> #{current_user.id}").includes(:user).order("vote_total DESC").paginate(:page => params[:page], :per_page => per_page)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @maps }
    end
  end

  def for_user
    @maps = Map.where(:user_id => params[:id])

    respond_to do |format|
      format.html { render :index }
      format.json { render json: @maps }
    end
  end

  # GET /maps/1
  # GET /maps/1.json
  def show
    @map = Map.find(params[:id], :include => "tiles")

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @map }
    end
  end

  # GET /maps/new
  # GET /maps/new.json
  def new
    @map = Map.new
    @map.user = current_user

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @map }
    end
  end

  # GET /maps/1/edit
  def edit
    get_map
  end

  # POST /maps
  # POST /maps.json
  def create
    @map = Map.new(params[:map])
    @map.user = current_user

    respond_to do |format|
      if @map.save
        # User automatically self-upvotes on creation
        map_vote = MapVote.find_or_create_by_map_id_and_user_id(@map.id, current_user.id)
        map_vote.vote = 1
        map_vote.save!
        @map.update_vote_total!

        format.html { redirect_to @map, notice: 'Map was successfully created.' }
        format.json { render json: @map, status: :created, location: @map }
      else
        format.html { render action: "new" }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /maps/1
  # PUT /maps/1.json
  def update
    get_map

    respond_to do |format|
      if @map.update_attributes(params[:map])
        format.html { redirect_to @map, notice: 'Map was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maps/1
  # DELETE /maps/1.json
  def destroy
    get_map
    @map.destroy

    respond_to do |format|
      format.html { redirect_to maps_url }
      format.json { head :no_content }
    end
  end

  def publish
    get_map
    @map.published = true
    @map.save!
		if params[:index] == "true"
			redirect_to maps_url
		else
    	redirect_to @map
		end
  end

  def unpublish
    get_map
    @map.published = false
    @map.save!
		if params[:index] == "true"
			redirect_to maps_url
		else
    	redirect_to @map
		end
  end

  def vote
    @map = Map.find(params[:id])
    vote = params[:vote].to_i
    if vote > 0
      vote = 1
    elsif vote < 0
      vote = -1
    else
      vote = 0
    end

    map_vote = MapVote.find_or_create_by_map_id_and_user_id(@map.id, current_user.id)
    if map_vote.vote == vote
      vote = 0
    end

    map_vote.vote = vote
    map_vote.save!

    @map.update_vote_total!

    render :partial => "map_info_inner", :locals => { :map => @map }
  end

  private
  def get_map
    @map = Map.find(params[:id], :include => "tiles")
    raise "Can't change someone else's map!" if @map.user != current_user
    raise "This map is a clone for a game and can't be modified" unless @map.real_map_id.nil?
    return @map
  end
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/maps/_map_info.html.erb
<div class="map-voting" data-ajax-url="<%=vote_map_path(map)%>">
	<%= render :partial => "maps/map_info_inner", :locals => { :map => map } %>
</div>

app/views/maps/_map_info_inner.html.erb
	<%
		vote = 0
		map_vote = MapVote.find_by_map_id_and_user_id(map.id, current_user.id)
		vote = map_vote.vote unless map_vote.nil?
	%>

	<table class="map-voting">
		<tr>
			<td>
				<div class="tool-button vote-button" data-map_id="<%=map.id%>" data-vote="1" data-tool_tag="<%= vote==1 ? "vote-up" : "vote-up-faded"%>"></div>
			</td>
			<td rowspan="2">
				<h1><%= map.name %> by <%= n(map.user) %></h1>
				<p><%= map.description %></p>
			</td>
		</tr>
		<tr>
			<td>
				<div class="tool-button vote-button" data-map_id="<%=map.id%>" data-vote="-1" data-tool_tag="<%= vote==-1 ? "vote-down" : "vote-down-faded"%>"></div>
			</td>
		</tr>
	</table>

app/views/maps/_map_line.html.erb
  <tr>
    <td><%= map.vote_total %></td>
    <td><%= map.name %></td>
    <td><%= map.user.nickname %></td>
    <td><%= link_to 'View', map, :class => "btn" %></td>
    <td><%= link_to 'Play a Game!', new_game_path(:map_id => map.id), :class => "btn btn-success" %></td>
    <% if map.user == current_user %>
    <td><%= link_to 'Edit', edit_map_path(map), :class => "btn" %></td>
    <td>
        <% if map.published == true %>
        <%= link_to 'Status: Public', unpublish_map_path(map, :index => "true"), method: :post, :class => "btn btn-success" %>
        <% else %>
        <%= link_to 'Status: Private', publish_map_path(map, :index => "true"), method: :post, :class => "btn btn-danger" %>
        <% end %>
    </td>
    <td><%= link_to 'Destroy', map, confirm: 'Are you sure?', method: :delete, :class => "btn btn-danger" %></td>
    <% else %>
    <td></td>
    <td></td>
    <td></td>
    <% end %>
  </tr>

app/views/maps/edit.html.erb
<h1>Editing map</h1>

<%= form_for(@map) do |f| %>
  <% if @map.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@map.errors.count, "error") %> prohibited this map from being saved:</h2>

      <ul>
      <% @map.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

  <div class="tile-buttons">
    <% for tile_type in TileType.all %>
      <div class="tile-button" data-tile_type_tag="<%=tile_type.tag %>"></div>
    <% end %>
  </div>

  <br class='clear'>

  <table class="map map-edit">
  	<%
  		x = 0
  		y = 0
  	%>
  	<tr>
  	<%= f.fields_for :tiles do |ft| %>
  		<% if x >= @map.width 
  			x = 0
  			y += 1 %>
  			</tr><tr>
  		<% end %>
  		<td class="tile" data-x="<%=x%>" data-y="<%=y%>" data-tile_type_tag="<%=ft.object.tile_type.tag %>"><%=ft.hidden_field :tile_type_tag%></td>
  		<% x += 1 %>
  	<% end %>
  		</tr>
  </table>

  <div class="actions">
    <input type="button" value="Clear Map" id="clear-map">
    <%= f.submit "Save Changes" %>
  </div>
<% end %>

<%= link_to 'Show', @map %> |
<%= link_to 'Back', maps_path %>

app/views/maps/index.html.erb
<h1>Listing maps</h1>

<div class="actions">
    <%= link_to 'Create a Map', new_map_path, :class => "btn btn-success" %>
</div>

<table class="table table-striped">
  <tr>
    <th>Score</th>
    <th>Name</th>
    <th>Author</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% unless @my_maps.nil? %>
    <% @my_maps.each do |map| %>
        <%= render :partial => "map_line", :locals => { :map => map } %>
    <% end %>
<% end %>

<% @maps.each do |map| %>
    <%= render :partial => "map_line", :locals => { :map => map } %>
<% end %>

</table>

<%= will_paginate @maps %>

<br />

app/views/maps/new.html.erb
<%= form_for(@map) do |f| %>
  <h2>New map</h2>

  <% if @map.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@map.errors.count, "error") %> prohibited this map from being saved:</h2>

      <ul>
      <% @map.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Map Name" %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :height %>
    <%= f.number_field :height %>
  </div>
  <div class="field">
    <%= f.label :width %>
    <%= f.number_field :width %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Map List', maps_path %>

app/views/maps/show.html.erb
<%= link_to 'Play a game on this map!', new_game_path(:map_id => @map.id), :class => "btn btn-success" %>
<% if @map.user == current_user %>
<%= link_to 'Edit this map', edit_map_path(@map), :class => "btn btn-primary" %>
  <% if @map.published == true %>
    <%= link_to 'Status: Public', unpublish_map_path(@map), method: :post, :class => "btn btn-success" %>
  <% else %>
    <%= link_to 'Status: Private', publish_map_path(@map), method: :post, :class => "btn btn-danger" %>
  <% end %>
<% end %>
<%= link_to 'Back to map list', maps_path, :class => "btn" %>



  <%= render :partial => "map_info", :locals => { :map => @map} %>


  <table class="map">
    <%
      x = 0
      y = 0
    %>
    <tr>
    <% for tile in @map.tiles %>
      <% if x >= @map.width 
        x = 0
        y += 1 %>
        </tr><tr>
      <% end %>
      <td class="tile" data-x="<%=x%>" data-y="<%=y%>" data-tile_type_tag="<%=tile.tile_type.tag %>" data-tile-variant="<%= rand(3) %>">
      </td>
      <% x += 1 %>
    <% end %>
      </tr>
  </table>


<% if @map.user == current_user and  @map.published == false %>
<div class="alert alert-error">
    This map is <b>PRIVATE</b>. Nobody can play it!  <%= link_to 'Publish this map.', publish_map_path(@map), method: :post, :class => "btn btn-success" %>
</div>
<% end %>