config/routes.rb
TestApp::Application.routes.draw do

  get "stats/index"
  get "stats/show"
  post "stats/search"

  resources :notifications do
    collection do
      post 'delete'
    end
    collection do
      get 'reload'
    end
  end

  resources :games do
    collection do
      post 'by_user'
    end

    member do
      get 'user'
      get 'add_unit'
      get 'move_unit'
      post 'end_turn'
      post 'surrender'
    end
  end

  get "welcome/index"

  devise_for :users

  resources :maps do
    collection do
      get 'for_user'
    end
    member do
      post 'vote'
      post 'publish'
      post 'unpublish'
    end
  end

  root :to => 'welcome#index'

end

app/models/notification.rb
class Notification < ActiveRecord::Base
	belongs_to :user
	belongs_to :game

	default_scope :order => "created_at DESC"

	def self.unread
		Notification.where(:viewed => 0)
	end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = current_user.notifications.dup

    Notification.update_all("viewed=1", "user_id=#{current_user.id}")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notifications }
    end
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
    @notification = current_user.notifications.where(:id => params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @notification }
    end
  end

  # GET /notifications/new
  # GET /notifications/new.json
  def new
    raise
    @notification = Notification.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @notification }
    end
  end

  # GET /notifications/1/edit
  def edit
    raise
    @notification = Notification.find(params[:id])
  end

  # POST /notifications
  # POST /notifications.json
  def create
    raise
    @notification = Notification.new(params[:notification])

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: 'Notification was successfully created.' }
        format.json { render json: @notification, status: :created, location: @notification }
      else
        format.html { render action: "new" }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /notifications/1
  # PUT /notifications/1.json
  def update
    raise
    @notification = Notification.find(params[:id])

    respond_to do |format|
      if @notification.update_attributes(params[:notification])
        format.html { redirect_to @notification, notice: 'Notification was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification = Notification.find(params[:id])
    @notification.destroy

    respond_to do |format|
      format.html { redirect_to notifications_url }
      format.json { head :no_content }
    end
  end

  def delete
    unless params[:delete].nil?
      for id in params[:delete]
        n = Notification.find_by_id_and_user_id(id, current_user.id)
        n.destroy unless n.nil?
      end
    end

    redirect_to notifications_path
  end

  def reload
    render :partial => "layouts/notifications"
  end

end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= form_for(@notification) do |f| %>
  <% if @notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% @notification.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing notification</h1>

<%= render 'form' %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<% if @notifications.length == 0 %>
  <h2>No notifications!</h2>
  <p>
    You need to make more friends.
  </p>
  <p>
    Or enemies.
  </p>
<% else %>
<h1>Listing notifications</h1>

<%= form_tag delete_notifications_path do %>
<table class="notifications table table-striped">
  <tr>
    <th>Delete?</th>
    <th>Message</th>
    <th>Game</th>
  </tr>

<% @notifications.each do |notification| %>
  <tr class="<%= notification.viewed==0 ? "unread" : "" %>">
    <td><%= check_box_tag "delete[]", notification.id, false, { :class=>"notification_delete" } %></td>
    <td>
      <%= simple_format((notification.viewed==0 ? "[NEW] " : "" ) + notification.message) %>
    </td>
    <td>
      <% unless notification.game.nil? %>
        <%= link_to "Game vs #{n(notification.game.opponent_for_user(current_user).user)}", notification.game %>
      <% end %>
    </td>
  </tr>
<% end %>
  <tr>
    <td><%= check_box_tag "check_all" %> Select All</td>
    <td></td>
    <td></td>
  </tr>
</table>
<div class="actions">
  <%= submit_tag "Delete Checked" %>
</div>
  <% end %>
<% end %>

app/views/notifications/new.html.erb
<h1>New notification</h1>

<%= render 'form' %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>