config/routes.rb
TestApp::Application.routes.draw do

  get "stats/index"
  get "stats/show"
  post "stats/search"

  resources :notifications do
    collection do
      post 'delete'
    end
    collection do
      get 'reload'
    end
  end

  resources :games do
    collection do
      post 'by_user'
    end

    member do
      get 'user'
      get 'add_unit'
      get 'move_unit'
      post 'end_turn'
      post 'surrender'
    end
  end

  get "welcome/index"

  devise_for :users

  resources :maps do
    collection do
      get 'for_user'
    end
    member do
      post 'vote'
      post 'publish'
      post 'unpublish'
    end
  end

  root :to => 'welcome#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
	has_many :players, :dependent => :destroy
	validate :uniqueness_of_players

	belongs_to :map, :dependent => :destroy

	before_create :clone_map, :start_new_turn!

	has_many :game_units, :dependent => :destroy

	has_many :notifications, :dependent => :destroy

	def clone_map
		cloned_map = self.map.dup
		cloned_map.real_map_id = self.map.id
		cloned_map.save!
		self.map = cloned_map
	end

	def uniqueness_of_players
		for player in self.players
			if self.players.index{ |p| p!=player && p.user==player.user }
				errors.add(:base, "LOL! Players can't play with themselves.  That's gross!")
			end
		end
	end

	def player_from_user(user)
		return Player.where(:game_id => self.id, :user_id => user.id).first
	end

	def player_from_team_id(team_id)
		for player in players
			return player if player.team_id == team_id
		end
		return nil
	end

	def current_player
		return player_from_team_id(self.current_team_id)
	end

	def current_user
		return current_player.user
	end

	def winning_player
		for player in players
			return player if player.id == self.winning_player_id
		end
		return nil

	end

	def winning_user
		return winning_player.user
	end

	def add_unit!(x, y, unit_tag, player)
		# Blocked by unit?
		return {:message => "Blocked by unit!"} unless get_game_unit_at(x,y).nil?

		unit = Unit.where(:tag => unit_tag).first
		tile = self.map.get_tile_at(x,y)

		return {:message => "Not enough money!"} if player.money < unit.cost

		# Adjacent to castle?
		return {:message => "Not adjacent to castle!"} unless tile.adjacent_to_castle?(player.team_id)

		# Blocked by unpassable terrain?
		return {:message => "Unpassable terrain!"} unless unit.can_enter_tile?(tile)

	    player.money -= unit.cost
	    player.save!

		game_unit = GameUnit.new( 
			:unit_id => unit.id, 
			:x => x, 
			:y => y, 
			:team_id => player.team_id,
			:current_hitpoints => unit.hitpoints,
			:movement_left => 0,
			:has_attacked => true 
			)

		self.game_units << game_unit
		self.save!
		return {:game_units=> [game_unit]}
	end

	def move_unit!(fromX, fromY, toX, toY, player)
		game_unit = get_game_unit_at(fromX, fromY)

		return {:message => "No unit at (#{x},#{y})!  JavaScript fail."} if game_unit.nil?

		return {:message => "Not your unit!"} if game_unit.team_id != self.current_team_id

		return {:message => "Out of movement!"} if game_unit.movement_left <= 0

		other_game_unit = get_game_unit_at(toX, toY)

		result = {}
		unless other_game_unit.nil?
			if other_game_unit.team_id == game_unit.team_id
				return {:message => "One of your units is in the way!"}
			else
				result = fight_unit!(game_unit, other_game_unit)
			end
		end

		if result.empty? or result[:target_died]==true
			move_unit_real!(fromX, fromY, toX, toY, player, game_unit)
		end

		if result[:game_units].nil?
			result[:game_units] = [game_unit]
		else
			result[:game_units] += [game_unit]
		end

		return result
	end

	def move_unit_real!(fromX, fromY, toX, toY, player, game_unit)
		fromTile = self.map.get_tile_at(fromX, fromY)
		toTile = self.map.get_tile_at(toX, toY)

		return {:message => "Unpassable terrain!"} unless game_unit.unit.can_enter_tile?(toTile)

		movementLeft = game_unit.unit.speed

		path = get_path(fromTile, toTile, movementLeft)

		return {:message => "Pathfinding failed."} if path.nil?
		
		game_unit.movement_left -= toTile.tile_type.movement_cost
		game_unit.movement_left = 0 if game_unit.movement_left < 0
		
		game_unit.x = path.last.x
		game_unit.y = path.last.y

		game_unit.save!
	end

	def fight_unit!(game_unit, other_game_unit)

		damage = game_unit.unit.damage

		min_damage = damage / 2

		damage = min_damage + rand(damage) + 1

		damage -= other_game_unit.unit.defense

		other_game_unit.current_hitpoints -= damage
		if other_game_unit.current_hitpoints <= 0
			other_game_unit.destroy
			player = self.players.where(:team_id => game_unit.team_id).first
			player.kills += 1
			player.save!
		else
			other_game_unit.save!
		end

		game_unit.has_attacked = true
		game_unit.movement_left = 0

		game_unit.save!

		return {
			:game_units => [game_unit, other_game_unit], 
			:kills => kill_totals,
			:units => unit_totals,
			:target_died => (other_game_unit.current_hitpoints <= 0)
		}
	end

	def kill_totals
		t = {}
		for p in self.players
			t["team#{p.team_id}_kills"] = p.kills
		end
		return t #self.players.map {|p| {"team#{p.team_id}_kills" => p.kills} }
	end

	def unit_totals
		t = {}
		for p in self.players
			t["team#{p.team_id}_units"] = game_units_for_player(p).length
		end
		return t
		#return self.players.map {|p| {"team#{p.team_id}_units" => game_units_for_player(p).length } }
	end

	def get_game_unit_at(x,y)
		if game_units.loaded?
			# FIXME: Change to a binary search?
			for game_unit in game_units
				return game_unit if game_unit.x==x and game_unit.y==y
			end
		else
			return game_units.where(:x => x, :y => y).first
		end

		return nil
	end

	def castles_for_player(player)
		castle_tag = "castle" + player.team_id.to_s

		tile_type = TileType.where(:tag => castle_tag)

		return self.map.tiles.where(:tile_type_id => tile_type)
	end

	def game_units_for_player(player)
		return self.game_units.where(:team_id => player.team_id)
	end

	def get_path(fromTile, toTile, movementLeft)
		return nil if movementLeft < 0

		return nil if fromTile.path_checked?
		fromTile.path_checked!

		for x in -1..1
			for y in -1..1
				#logger.info "Checking tile at (#{fromTile.x + x}, #{fromTile.y + y})"
				t = self.map.get_tile_at(fromTile.x + x, fromTile.y + y)
				return [t] if toTile == t
			end
		end

		return nil
	end

	def max_team_id
		return self.players.maximum(:team_id)
	end

	def end_turn!
		# Delete all notifications about this game
		# This line only destroys in memory?!?
		self.notifications.destroy
		# So we need to call this explcitly?  FIXME: There must be another function that does both?
		Notification.destroy_all(:game_id => self.id)

		# Flip castles
		for game_unit in self.game_units.where(:team_id => self.current_team_id)
			# Capture castles, if a unit is standing on one.
			tile = self.map.get_tile_at(game_unit.x, game_unit.y)
			if tile.tile_type.tag == "neutral_castle"
				tile.tile_type = TileType.where(:tag => ("castle" + self.current_team_id.to_s)).first
				tile.save!
			elsif tile.tile_type.tag =~ /^castle(\d+)$/
				if $1.to_i != self.current_team_id
					tile.tile_type = TileType.where(:tag => "neutral_castle").first
					tile.save!
				end
			end
		end

		self.current_team_id += 1
		if self.current_team_id > max_team_id
			self.current_team_id = 0
		end

		# Check for a winner
		update_winning_player_id

		if self.winning_player_id.nil?
			start_new_turn!()		
		end

		self.turn_counter += 1

		self.save!
	end

	def update_winning_player_id
		for player in self.players
			if castles_for_player(player).length == 0# or game_units_for_player(player).length == 0
				winning_player = self.players.where('team_id <> ?',player.team_id).first
				set_winning_player(winning_player)

				adjust_ratings(winning_player, player)

				notification = Notification.create(
						:game_id => self.id,
						:user_id => player.user.id,
						:message => "You were defeated!"
					)
				return
			end
		end
	end

	def set_winning_player(winning_player)
		self.winning_player_id = winning_player.id
		self.current_team_id = -winning_player.team_id
	end

	def user_surrender!(user)
		player_surrender!(player_from_user(user))
	end

	def player_surrender!(player)
		if self.turn_counter <= 1
			cancel_game!(player)
			return
		end

		winner = opponent_for_player(player)
		set_winning_player( winner )
		self.save!
		notification = Notification.create(
				:game_id => self.id,
				:user_id => winning_user.id,
				:message => "Your opponent surrendered!"
			)
		adjust_ratings(winner, player)
	end

	def cancel_game!(player)
		winner = opponent_for_player(player)
		self.winning_player_id = nil
		self.current_team_id = -1
		self.save!

		notification = Notification.create(
				:game_id => self.id,
				:user_id => winner.user.id,
				:message => "Your opponent canceled the game on the first turn, so your rating is unaffected."
			)
	end

	def is_active?
		return self.current_team_id >= 0
	end

	def is_draw?
		return (!self.is_active?() and self.winning_player_id.nil?)
	end


	def adjust_ratings(winner, loser)
		winner.user.xp += 10
		loser.user.xp  += 5

		# winning = 1
		# losing  = 0

		expected_score_winner = 1.0 / (  1.0 + 
				(
					10.0**((loser.user.elo.to_f - winner.user.elo.to_f) / 400.0) 
				)
			)


		expected_score_loser = 1.0 / (  1.0 + 
				(
					10.0**((winner.user.elo.to_f - loser.user.elo.to_f) / 400.0) 
				)
			)

		k = 32.0

		change_winner = k * (1.0 - expected_score_winner)
		change_loser  = k * (0.0 - expected_score_loser)

		winner.user.elo += change_winner.to_i
		loser.user.elo += change_loser.to_i

		winner.user.wins += 1
		loser.user.loses += 1

		winner.user.save!
		loser.user.save!
	end

	def opponent_for_user(user)
		return opponent_for_player(player_from_user(user))
	end

	def opponent_for_player(player)
		for p in self.players
			if player != p
				return p
			end
		end		
	end

	def start_new_turn!
		# Generate income
		for player in self.players
			if player.team_id == self.current_team_id
				player.money += castles_for_player(player).length * 5
				player.save!
			end
		end


		# Reset all the units
		for game_unit in self.game_units.where(:team_id => self.current_team_id)
			game_unit.movement_left = game_unit.unit.speed
			game_unit.has_attacked = false
			game_unit.save!
		end

		unless self.id.nil?
			notification = Notification.create(
					:game_id => self.id,
					:user_id => current_user.id,
					:message => "It's your turn!"
				)
		end
	end


end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  # GET /games
  # GET /games.json
  def index
    if params[:id].blank?
				raise "Disabled global game listing for performance reasons."
        @games = Game.order("winning_player_id DESC")
    else
        #@games = Game.find(:all,
        #    :conditions => "games.id IN (SELECT players.game_id FROM players WHERE players.user_id=#{params[:id]})",
        #    :include => [{:players => :user}, :map],
        #    :order => "winning_player_id DESC"
        #  ).page(params[:page])
        @games = Game.where(
						"games.id IN (SELECT players.game_id FROM players WHERE players.user_id=#{params[:id]})",
            :include => [{:players => :user}, :map]).order("winning_player_id DESC").paginate(:page => params[:page], :per_page => 20)
    end

    #@users = User.order("nickname")

    respond_to do |format|
      format.html { render :index }
      format.json { render json: @games }
    end
  end

  def user
    index
  end

  # GET /games/1
  # GET /games/1.json
  def show
    # Right now anyone can watch anyone's game, which I think is fine -- so long as they can't modify anything.
    # Riot Games: 2 years to add spectator mode
    # Quill18: About 4 hours into the project.

    @game = Game.find(params[:id], :include => [{:map => {:tiles => :tile_type}}, {:game_units => :unit}, :players])
    logger.info "PRE-CACHED GAME DETAILS"
    @player = @game.player_from_user(current_user)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/new
  # GET /games/new.json
  def new
    @game = Game.new

    @game.map_id = params[:map_id]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @game }
    end
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(params[:game])

    params[:user_ids].unshift(current_user.id)
    team_id = 0

    for user_id in params[:user_ids]
      user = User.find(user_id)
      player = Player.new( :user => user, :team_id => team_id )
      player.money = @game.map.starting_money
      team_id += 1
      @game.players << player
    end


    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render json: @game, status: :created, location: @game }
      else
        format.html { render action: "new" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_unit
    get_game

    response = @game.add_unit!(params[:x].to_i, params[:y].to_i, params[:unit_tag], @player)
    response["money"] = { "team#{@player.team_id}_money" => @player.money }

    respond_to do |format|
      format.json { render json: response.to_json( :include => :unit ) }
    end

#    if @game_unit.class == GameUnit
#      respond_to do |format|
#        format.json { render json: { unit_tag: @game_unit.unit.tag, money: @player.money } }
#      end
#    else
#      respond_to do |format|
#        format.json { render json: { message: @game_unit } }
#      end
#    end
  end

  def move_unit
    get_game

    response = @game.move_unit!(params[:fromX].to_i, params[:fromY].to_i, params[:toX].to_i, params[:toY].to_i, @player)

    respond_to do |format|
      format.json { render json: response.to_json( :include => :unit ) }
    end
  end

  def end_turn
    get_game
    @game.end_turn!
    redirect_to @game
  end

  def surrender
    get_game
    @game.user_surrender!(current_user)
    redirect_to user_game_path(current_user.id)
  end

  private
  def get_game
    @game = Game.find(params[:id], :include => [{:map => :tiles}])
    @player = @game.player_from_user(current_user)
    raise "Not your turn!" if @player != @game.current_player
  end

end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_game_map.html.erb
  <table class="map map-game" data-add-unit-path="<%= add_unit_game_path(@game) %>" data-move-unit-path="<%= move_unit_game_path(@game) %>">
  	<%
  		x = 0
  		y = 0
  	%>
  	<tr>
  	<% for tile in @game.map.tiles %>
  		<% if x >= @game.map.width 
  			x = 0
  			y += 1 %>
  			</tr><tr>
  		<% end %>
  		<td class="tile" data-x="<%=x%>" data-y="<%=y%>" data-tile_type_tag="<%=tile.tile_type.tag %>" data-tile-variant="<%= rand(3) %>">
        <% game_unit = @game.get_game_unit_at(x,y) %>
        <% unless game_unit.nil? %>
          <div class="unit" data-unit_id="<%=game_unit.id%>" data-unit_tag="<%=game_unit.unit.tag%>" data-team_id="<%=game_unit.team_id%>">
            <div class="shield">
              <span class="movement"><%= game_unit.movement_left %></span>
            </div>
            <div class="healthbar" data-percentage="<%= 100*game_unit.current_hitpoints/game_unit.unit.hitpoints %>"></div>
          </div>
        <% end %>
      </td>
  		<% x += 1 %>
  	<% end %>
  		</tr>
  </table>

app/views/games/_game_sidepanel.html.erb
<div class="game_sidepanel">
	<%= render :partial => "scoreboard" %>
	<div class="panel_tile_info">
	</div>
	<div class="panel_unit_info">
		<%= render :partial => "panel_unit_info" %>
	</div>
</div>

app/views/games/_game_tools.html.erb
<div class="game_tools">
  <% if @player.team_id == @game.current_team_id %>
  <h2>Move Units</h2>
  <div class="tool-button" data-tool_tag="pointer"></div>
  <br class="clear">
  <h2>Build Units</h2>
  <% for unit in Unit.all %>
    <div class="unit-button" data-unit_tag="<%=unit.tag %>"></div>
  <% end %>
  <br class="clear">
  <br class="clear">
	  <div class="actions">
    <%= button_to "End Turn", end_turn_game_path(@game), :class => "btn btn-success" %>

    <% if @game.turn_counter <= 1 %>
      <%= button_to "Cancel Game", surrender_game_path(@game), :class => "btn btn-danger", :confirm => "Cancel this game?" %>
    <% else %>
      <%= button_to "Surrender", surrender_game_path(@game), :class => "btn btn-danger", :confirm => "Give up?!?" %>
    <% end %>
  </div>
  <% end %>
</div>

app/views/games/_panel_unit_info.html.erb
<%
	tile_types = TileType.all
%>
<% for tile_type in tile_types %>
<div class="tile_type_info" data-tile_type_tag="<%=tile_type.tag%>">
	<table class="tile_type_info">

		<tr>
			<th colspan="2">
				<%= tile_type.name %>
			</th>
		</tr>
		<tr>
			<td>Movement Cost</td>
			<td><%= tile_type.movement_cost==0 ? "Blocked" : tile_type.movement_cost %></td>
		</tr>
		<tr>
			<td>Special</td>
			<td>
				<% if tile_type.is_bubble_wall==1 %>
					Bubbles!
				<% elsif tile_type.tag =~ /castle/ %>
					Gives Food!
				<% else %>
					Nothing
				<% end %>
			</td>
		</tr>
	</table>
</div>
<% end %>

<%
	units = Unit.all
%>
<% for unit in units %>
<div class="unit_info" data-unit_tag="<%=unit.tag%>">
	<table class="unit_info">

		<tr>
			<th colspan="2">
				<%= unit.name %>
			</th>
		</tr>
		<tr>
			<td>Max HPs</td>
			<td><%= unit.hitpoints %> <i class="icon-heart"></i>
 </td>
		</tr>
		<tr>
			<td>Attack</td>
			<td><%= unit.damage %> <i class="icon-arrow-up"></td>
		</tr>
		<tr>
			<td>Defense</td>
			<td><%= unit.defense %> <i class="icon-arrow-down"></td>
		</tr>
		<tr>
			<td>Speed</td>
			<td><%= unit.speed %> <i class="icon-forward"></td>
		</tr>
		<tr>
			<td>Cost</td>
			<td><%= unit.cost %> <i class="icon-star"></td>
		</tr>
		<tr>
			<td>Special</td>
			<td><%= unit.is_bubble_walker==true ? "Likes Bubbles" : "Nothing"%></td>
		</tr>
	</table>
</div>
<% end %>

app/views/games/_scoreboard.html.erb
	<div class="scoreboard turn">
		<table class="scoreboard">
			<tr>
				<th colspan="2">
					<% if @game.is_active? %>
						<%= @game.current_player.user.nickname %>'s turn #<%= (@game.turn_counter.to_i/2).floor + 1 %>
					<% else %>
							Ended 
						on turn #<%= (@game.turn_counter/2).floor + 1 %>
					<% end %>
				</th>
			</tr>
		</table>
	</div>


	<% for team_id in 0..1 %>
<div class="scoreboard team<%=team_id%>">
<table class="scoreboard">
		<% player = @game.players.where(:team_id => team_id).first %>
	<tr>
		<th colspan="2">
			Team <%= team_id == 0 ? "Red" : "Blue" %>: <%= player.user.nickname %>
		</th>
	<% if @game.winning_player_id == player.id %>
	<tr>
		<th colspan="2">
				<b>WINNER!</b>
		</th>
	</tr>
	<% end %>
	</tr>
	<tr>
		<td colspan="2">
			<%= player.user.nickname %>
		</td>
	</tr>
	<tr>
		<td>
			Fish Food
		</td>
		<td id="team<%=team_id%>_money">
			<%= player.money %>
		</td>
	</tr>
	<tr>
		<td>
			Castles
		</td>
		<td id="team<%=team_id%>_castles">
			<%= @game.castles_for_player(player).length %>
		</td>
	</tr>
	<tr>
		<td>
			Units
		</td>
		<td id="team<%=team_id%>_units">
			<%= @game.game_units_for_player(player).length %>
		</td>
	</tr>
	<tr>
		<td>
			Kills
		</td>
		<td id="team<%=team_id%>_kills">
			<%= player.kills %>
		</td>
	</tr>
</table>
</div>
	<% end %>


<% unless @player.nil? %>
	<input type="hidden" id="player_id" value="<%= @player.id %>">
	<input type="hidden" id="current_team_id" value="<%= @game.current_team_id %>">
	<input type="hidden" id="current_player_id" value="<%= @game.current_player.nil? ? "" : @game.current_player.id %>">
	<% unless @game.winning_player_id.nil? %>
		<input type="hidden" id="winning_player_id" value="<%= @game.winning_player_id %>">
	<% end %>
<% end %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<div class="actions">
  <%= link_to 'Start a New Game', new_game_path, :class => "btn btn-success" %>
</div>

<table class="game-list table table-striped">
  <tr>
    <th>Players</th>
    <th>Map</th>
    <th>Status</th>
    <th></th>
  </tr>

<% @games.each do |game| %>
  <tr>
    <td><%= game.players.map {|p| n(p.user)}.join(", ") %></td>
    <td><%= game.map.name %></td>
    <% if game.is_active? %>
          <td class="<%= !game.current_player.nil? and game.current_player.user==current_user ? "your-turn" : ""%>">
            <%= n(game.current_player.user) %>'s Turn
          </td>
    <% else %>
      <td>
        <%= game.is_draw? ? "Cancelled" : "Winner: #{n(game.winning_player.user)}" %>
      </td>
    <% end %>
    <td>
        <% if game.is_active? and !current_user.nil? and !current_user.games.index(game).nil? %>
          <%= link_to 'Play!', game, :class => "btn #{game.current_player.user == current_user ? "btn-success" : ""}" %>
        <% else %>
          <%= link_to 'View', game, :class => "btn" %>
        <% end %>
    </td>
  </tr>
<% end %>
</table>

<%= will_paginate @games %>

<br />

app/views/games/new.html.erb
<%= form_for(@game) do |f| %>
  <h2>New game</h2>

  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>Real match-making and online player lists coming Soon&#0153;.</p>

  <div class="field">
    <label>Map</label>
    <%= f.select :map_id, Map.where(:real_map_id => nil, :published => true).map {|m| [m.name, m.id]} %>
  </div>

  <div class="field">
  	<label>Who to challenge?</label>
  	<%= select_tag "user_ids[]", options_from_collection_for_select(
            User.where(['id <> ?', current_user.id]).order("nickname"),
            :id, :nickname) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<%
	real_map = Map.find_by_id(@game.map.real_map_id)
	if real_map.nil?
		real_map = @game.map
	end
%>
<%= render :partial => "maps/map_info", :locals => { :map => real_map } %>
	
<div class="game-container">
	<%= render :partial => "game_sidepanel" %>
	<%= render :partial => "game_map" %>
	<% if !@player.nil? and @game.winning_player_id.nil? %>
		<%= render :partial => "game_tools" %>
	<% end %>
</div>

<br class="clear">

<%= link_to 'Back to Game List', games_path %>