config/routes.rb
TestApp::Application.routes.draw do

  get "stats/index"
  get "stats/show"
  post "stats/search"

  resources :notifications do
    collection do
      post 'delete'
    end
    collection do
      get 'reload'
    end
  end

  resources :games do
    collection do
      post 'by_user'
    end

    member do
      get 'user'
      get 'add_unit'
      get 'move_unit'
      post 'end_turn'
      post 'surrender'
    end
  end

  get "welcome/index"

  devise_for :users

  resources :maps do
    collection do
      get 'for_user'
    end
    member do
      post 'vote'
      post 'publish'
      post 'unpublish'
    end
  end

  root :to => 'welcome#index'

end

app/views/layouts/_fish_name.html.erb
<%
fish_names = ["Afra Cichlid",
"African Butterfly Cichlid",
"African Butter Catfish",
"African Knife Fish",
"African Snakehead",
"Agassiz' Dwarf Cichlid",
"Akar betta",
"Albino Cory",
"El Abra Pygmy Swordtail",
"Amiet's Lyretail",
"Asian Arowana",
"Archerfish",
"Argus Fish",
"Arnoldi",
"Aulonocara Maulana",
"Aulonocara Benga",
"Australian Pearl Arowana",
"Azureus Cichlid",
"Badis",
"Bala Shark",
"Banded Knife Fish",
"Bangka Snakehead",
"Baram Snakehead",
"Barca Snakehead",
"Batik Loach",
"Banded Bichir",
"Banded Shovelnose Catfish",
"Barred Knife Fish",
"Barred Sorubim",
"Bearded Cory",
"Beauty Mouthbrooder",
"Bengal Danio",
"Bigtooth River Stingray",
"Bishop livebearer",
"Black Arowana",
"Black Banded Leporinus",
"Black Barred Myleus",
"Black Diamond Gold Piranha",
"Blackfinned Snakehead",
"Black Ghost Knife",
"Black Neon Tetra",
"Black Piranha",
"Black Phantom tetra",
"Blackskirt Tetra",
"Bleeding Heart Tetra",
"Benny Tetra",
"Blue Gourami",
"Blue Discus",
"Big Eye Mouthbrooder",
"Big Toothed Piranha",
"Black Pacu",
"Black Small Fighter",
"Blind Cavefish",
"Bloodfin Tetra",
"Blotched Snakehead",
"Blue Acara",
"Blue Band Mouthbrooder",
"Blue Convict Cichlid",
"Blue Panda Apisto",
"Bluespotted Snakehead",
"Blyth's Loach",
"Bolivian ram",
"Brandti Piranha",
"Bream",
"Brilliant rasbora",
"Bristlenosed Catfish",
"Brown Betta",
"Brown's Betta",
"Brown Discus",
"Bucktoothed Tetra",
"Buenos Aires Tetra",
"Bulldog Pleco",
"Bullseye Snakehead",
"Burmese Snakehead",
"Cardinal Tetra",
"Catemaco Livebearer",
"Celebes Halfbeak",
"Ceylon Snakehead",
"Chel Snakehead",
"Cherry Barb",
"Chevron Snakehead",
"Chilumba",
"Chinese Snakehead",
"Cinnamon Killifish",
"Clown Barb",
"Clown Killifish",
"Clown Killi",
"Clown Knife Fish",
"Clown Loach",
"Clown Pleco",
"Cockatoo dwarf Cichlid",
"Comma Swordtail",
"Compressed Cichlid",
"Congo Blackfin",
"Congo Tetra",
"Convict Cichlid",
"Coolie Loach",
"Cortes Swordtail",
"Cross River Puffer",
"Crystel Eyed Catfish",
"Cochu's Blue Tetra",
"Demasoni Cichlid",
"Diamond tetra",
"Dovii Cichlid",
"Double Lipspot Mouthbrooder",
"Duckbill Catfish",
"Dusky Piranha",
"Dwarf Croaking Gourami",
"Dwarf Gourami",
"Dwarf Livebearer",
"Dwarf Loach",
"Dwarf Mouthbrooder (Betta)",
"Dwarf Snakehead",
"Duboisi Cichlid",
"Electric Blue Hap",
"Electric Catfish",
"Electric Yellow Lab",
"El Quince Swordtail",
"Emperor Snakehead",
"Eureka Cichlid",
"Eyespot Mouthbrooder",
"Fahaka Puffer",
"Father Strohs Mouthbrooder",
"Figure Eight Puffer",
"Firebird Cichlid",
"Firemouth Cichlid",
"Firehead cichlid",
"Flag acara",
"Flagtailed Catfish",
"Flame Tetra",
"Flier Cichlid",
"Forrest Betta",
"Freshwater Barracuda",
"Freshwater Butterflyfish",
"Freshwater Garfish",
"Freshwater Moray Eel",
"Frontosa Cichlid",
"Fundulopanchax avichang",
"Fundulopanchax batesii",
"German Blue Ram",
"Geryi Piranha",
"Ghost Knife Fish",
"Giant Betta",
"Giant Danio",
"Giant Snakehead",
"Glass Knife Fish",
"Glass catfish",
"Glowlight Tetra",
"Golden Nugget Pleco",
"Golden Snakehead",
"Gold Gourami",
"Gold Mixteco",
"Grant's Peacock cichlid",
"Gray Bichir",
"Green Discus",
"Green terror",
"Green Throat Mouthbrooder",
"Green Puffer",
"Green Severum",
"Green Terror Cichlid",
"Guppy",
"Guyana Leaffish",
"Halfbeak",
"Heller's Cichlid",
"High Backed Pygme Swordtail",
"Highland Platy",
"Highland Swordtail",
"Hikari Danio",
"Hogchoker",
"Holland's Piranha",
"Honey Gourami",
"Hoplo Catfish",
"Hora's Loach",
"Horsefaced Loach",
"Humeralis Piranha",
"Indian Glassfish",
"Indonesian Datnoid",
"Inle Snakehead",
"Jack Demspey Cichlid",
"Javan Mouthbrooding Fighting Fish",
"Jelly Bean Tetra",
"Julii Cory",
"Kadango Cichlid",
"Keyhole Cichlid",
"Knife Livebearer",
"Koi Carp",
"Lamp eye tetra",
"Leopard Danio",
"Leopard Cory",
"Leporinus",
"Lesser Bleeding Heart Tetra",
"Lesser Spiny Eel",
"Lyretail Killifish",
"Lyre Tail Pleco",
"Madagascar Rainbowfish",
"Maison's Peacock",
"Malawi Eyebiter",
"Malebo Puffer",
"Marbled Hatchet",
"Marbled Headstander",
"Mbu Puffer",
"Mekong Puffer",
"Midas Cichlid",
"Monterray Platy",
"Montezuma Swordtail",
"Moonlight Gourami",
"Mossaic Stingray",
"Motoro Sting Ray",
"Mousetail Knife fish",
"Muzquiz Platy",
"Neon Tetra",
"New Ediths Mouthbrooder",
"Niger Snakehead",
"Night Snakehead",
"Nijsseni's Dwarf Cichlid",
"Norman's Lampeye",
"Northern Mountain Swordtail",
"Northern Platy",
"Northern Snakehead",
"Ocellated Puffer Fish",
"Ocellated Snakehead",
"Otocinclus",
"Olive Danio",
"One Spot Mouthbrooder",
"Oscar",
"Orange Finned Danio",
"Orangespotted Snakehead",
"Ornate Bichir",
"Ornate Pim",
"Ornate Tetra",
"Oscar Fish",
"Otocinclus Catfish",
"Pacman catfish",
"Panaw Snakehead",
"Panda cory",
"Paradise Fish",
"Pareutropius bueffei",
"Peaceful Betta",
"Peacock Mouthbrooder",
"Pearl Danio",
"Pearl Gourami",
"Penguin Tetra",
"Peppered Corydoras",
"Pepper Tetra",
"Pictus Catfish",
"Pike Livebearer",
"Pike Piranha",
"Pineapple Discus",
"Pinche Piranha",
"Pingi Logsucker",
"Pink Tailed Chalceus",
"Piraya Piranha",
"Platy",
"Plumed Lyretail",
"Polka Dot Loach",
"Polka Dot Ray",
"Powder Blue Cichlid",
"Pretty Tetra",
"Purple Spotted Gudgeon",
"Queen Loach",
"Rainbow Snakehead",
"Rainbow Shark",
"Red Belly Pacu",
"Redbelly Piranha",
"Red-blotched River Stingray",
"Redbreast acara",
"Red Devil",
"Red Dwarf Rasbora",
"Red Empress Cichlid",
"Red Eyed Tetra",
"Red Heckles Discus",
"Red Hook Silver Dollar",
"Red jewel cichlid",
"Redish Dwarf Fighter",
"Red Port Acara",
"Red Sumatran Fighter",
"Red Tailed Catfish",
"Red Tailed Hemiodopsis",
"Red Tailed Shark",
"Red Terror Cichlid",
"Red Zebra",
"Rio Aloyac Platy",
"Rose Danio",
"Rosen's Hybrid Platy",
"Royal pleco",
"Rummy Nose Tetra",
"Rummynose Tetra",
"Sabretooth Tetra",
"Sailfin Molly",
"Sailfin Pim",
"San Juan Cory",
"Schallers Mouthbrooder",
"Schwartz's Cory",
"Scissortail",
"Serrated Piranha",
"Serpae Tetra",
"Sheepshead Swordtail",
"Severum",
"Siamese Algae Eater",
"Siamese Fighting Fish",
"Sieve Cichlid",
"Silver Datnoid",
"Silver Dollar",
"Silver hatchetfish",
"Silver Hemiodopsis",
"Silver Mylossoma",
"Silver Prochilodus",
"Silvertip Tetra",
"Simple Mouthbrooder",
"Simor Fighter",
"Skunk Botia",
"Skunk Cory",
"Slender Betta",
"Slender Hemiodus",
"Slender Pygme Swordtail",
"Small Fin Fighter",
"Smaragd Fighting Fish",
"Smooth Back River Stingray",
"Snakeskin Gourami",
"Spike Tail Platy",
"Splendid Snakehead",
"Spotted Pike Characin",
"Speckled Platy",
"Spotted cachorro",
"Spotted Green Puffer",
"Spotted Silver Dollar",
"Spotted Snakehead",
"Spotted Talking Catfish",
"Socolof's Tetra",
"Sterbai Cory Cat",
"Sterlet",
"Striped barb",
"Striped Silver Dollar",
"Striped Panchax",
"Swordtail",
"Swordtail Characin",
"Tail Light Tetra",
"T-Bar Cichlid",
"Tenuis Tetra",
"Ten Spotted Livebearer",
"Texas Cichlid",
"Three Lined Cory",
"Thick Lib Gourami",
"Thinbar Datnoid",
"Three lined mouthbrooder",
"Three Spot Tetra",
"Tiger Barb",
"Tiger Botia",
"Tiretrack Eel",
"Tomi Mouthbrooder",
"Tigrinus Catfish",
"Tramitichromis intermedius",
"Tricolor Cichlid",
"Twin Spot Flag Cichlid",
"Turquoise Cichlid",
"Tussys Small Red Fighter",
"Umbie",
"Umbrella Cichlid",
"Upland Swordtail",
"Upside-down Catfish",
"Viejita Apisto",
"Wasers Mouthbrooder",
"Wessel's Cichlid",
"West African Lungfish",
"Western Mosquitofish",
"White Cloud Mountain Minnow",
"White Piranha",
"Widebar Datnoid",
"Wimple Piranha",
"Wine Red Betta",
"Wolf Fish",
"Yellow Acara",
"Yellow King Piranha",
"Yellow Swordtail",
"YoYo Loach",
"Zebra Danio",
"Zebra Loach ",
"Zoidberg"]
%>
<%= fish_names[rand(fish_names.length)] %>

app/views/layouts/_notifications.html.erb
				<a href="<%= url_for notifications_path %>">
				<% if current_user.notifications.unread.length > 0 %>
					<i class="icon-envelope icon-white"></i> (<span id="new_notifications"><%= current_user.notifications.unread.length %></span>)
				<% else %>
					<i class="icon-envelope"></i>
				<% end %>
				</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fish Tank Commander</title>
  <link href='http://fonts.googleapis.com/css?family=Bitter:400,700' rel='stylesheet' type='text/css'>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>


</head>
<body class="<%=controller_name%> <%=action_name%>">

<header>
	<h1><%= link_to "FISH TANK COMMANDER", root_path %></h1>
	<h2><%= link_to "Big Combat in a Tiny Aquarium."%></h2>


	<nav>
		<% if user_signed_in? %>
			<h3>Hi <%=current_user.nickname%>, you're my favorite <%= render :partial => "layouts/fish_name" %>!</h3>
		<% else %>
			<h3>Sign up for hours and hours of recognition in this spot!</h3>
		<% end %>
		<ul>
			<% if user_signed_in? %>
			<li><%= link_to "Logout", destroy_user_session_path(current_user), :method => :delete %></li>
			<li><%= link_to "Account Settings", edit_user_registration_path(current_user) %></li>
			<li><%= link_to "View/Create Maps", maps_path %>
			<li><%= link_to "Leaderboard", stats_index_path %>
			<li><%= link_to "Play a Game!", user_game_path(current_user.id) %>
			<li id="toolbar_notifications" data-ajax-url="<%= reload_notifications_path %>"><%= render :partial => "layouts/notifications" %></li>
			<% else %>
			<li><%= link_to "Log in!", new_user_session_path %></li>
			<li><%= link_to "View/Create Maps", maps_path %>
			<li><%= link_to "Leaderboard", stats_index_path %>
			<li><%= link_to "Play a Game!", new_user_session_path %>
			<% end %>
		</ul>
	</nav>
</header>

<section id="alerts">
	<% unless flash[:notice].blank? %>
		<div class="alert alert-success"><%= flash[:notice] %></div>
	<% end %>
	<% unless flash[:alert].blank? %>
		<div class="alert alert-error"><%= flash[:alert] %></div>
	<% end %>
</section>

<div class="content">
	<%= yield %>
</div>

<div id="ajax_waiting">
	Waiting on server...
</div>

<footer>
	<p>Fish Tank Commander is &copy; 2012 <a href="mailto:quill18@towerdive.com">Martin "quill18" Glaude</a> - Made alone in 48 hours...but with lots of suggestions and testing from my super-duper-awesome <a href="http://youtube.com/quill18">viewers</a>!</p>
	<p>
		<a href="https://github.com/quill18/ld23-tiny-world/issues">Please report any issues here.</a>
	</p>
</footer>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-31116422-1']);
  _gaq.push(['_setDomainName', 'fishtankcommander.com']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

</body>
</html>